In [1]:
import pandas as pd
from numpy import array
import datetime as dt

from pyspark.sql import SQLContext
from pyspark.mllib.clustering import KMeans, KMeansModel

import utils
%matplotlib inline

# Step 1: Attribute Selection

Read the contents of `users.csv` and calculate user age based on dob

In [2]:
gameClicksDF = pd.read_csv('./flamingo-data/game-clicks.csv')
gameClicksDF = gameClicksDF.rename(columns=lambda x: x.strip())
# select useful features
selectGameClicksDF = gameClicksDF[['userId', 'userSessionId', 'teamId', 'teamLevel', 'isHit']]
# aggregate to get hit count
hitsPerUserSession = selectGameClicksDF.groupby(['userId','userSessionId', 'teamId', 'teamLevel']).sum()
hitsPerUserSession = hitsPerUserSession.reset_index()
hitsPerUserSession.columns = ['userId','userSessionId', 'teamId', 'teamLevel', 'hitCounts'] #rename the columns

hitsPerUserSession.sort(['userId'])



/home/cloudera/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:10: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


userId  userSessionId  teamId  teamLevel  hitCounts
0          0          23473     157          1         28
1          0          24943     157          2         35
2          0          28377     157          3         32
3          0          32029     157          4         29
4          0          37439     157          5         19
12         1          34802      99          8         12
11         1          26938      99          7         16
10         1          21014      99          6         11
9          1          16232      99          5         13
7          1          10041      99          3          9
6          1           7847      99          2         14
5          1           5835      99          1          7
8          1          12713      99          4         14
18         2          34304      22          8          4
13         2          12107      22          3          0
14         2          12411      22          4          3
15         2          15899      22          5          6
16         2          20628      22          6          3
17         2          26505      22          7          6
20         6          34684      77          8         11
19         6          28628      77          7          5
21         8          27410     124          4          1
22         8          27918     124          5         23
23         8          33190     124          6         14
29         9          26931      97          7         13
28         9          21009      97          6         14
27         9          16228      97          5          8
30         9          34794      97          8          8
25         9          10038      97          3          7
24         9           9187      97          2          1
...      ...            ...     ...        ...        ...
5718    2383           7522       8          2         23
5723    2383          26391       8          7         14
5724    2383          34179       8          8         13
5722    2383          20525       8          6         14
5717    2383           5958       8          1         13
5720    2383          12326       8          4         24
5719    2383           9682       8          3         16
5721    2383          15806       8          5         24
5732    2384          34335      27          8          9
5731    2384          26532      27          7         15
5729    2384          15918      27          5         16
5730    2384          20652      27          6          9
5727    2384           9777      27          3          6
5726    2384           7610      27          2          6
5725    2384           5934      27          1          5
5728    2384          12428      27          4         15
5733    2386          22026      77          6         11
5734    2386          26831      77          7         15
5735    2386          34682      77          8          6
5737    2387          32030     157          4         40
5736    2387          28629     157          3         40
5738    2387          37440     157          5         17
5743    2389          16020      57          5         19
5744    2389          20768      57          6         13
5742    2389          12525      57          4         16
5745    2389          26657      57          7         21
5740    2389           7697      57          2         13
5739    2389           6929      57          1          6
5741    2389           9868      57          3         13
5746    2389          34482      57          8          4

[5747 rows x 5 columns]

Read the contents of the file `buy-clicks.csv` and removes any extra whitespaces.

In [3]:
buyclicksDF = pd.read_csv('./flamingo-data/buy-clicks.csv')
buyclicksDF = buyclicksDF.rename(columns=lambda x: x.strip()) #removes whitespaces from headers

# select useful fields
selectBuyclicksDF = buyclicksDF[['userId', 'userSessionId', 'team', 'price']]
selectBuyclicksDF = selectBuyclicksDF.rename(columns = {'team':'teamId'})
# selectBuyclicksDF.sort(['userId', 'userSessionId'])

# aggregate to get average buys per user
buysPerUserSession = selectBuyclicksDF.groupby(['userId', 'userSessionId', 'teamId']).mean()
buysPerUserSession = buysPerUserSession.reset_index()
buysPerUserSession.columns = ['userId', 'userSessionId', 'teamId', 'avgPrice']
buysPerUserSession.sort(['userId', 'userSessionId'])


/home/cloudera/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:13: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


userId  userSessionId  teamId   avgPrice
0          1          10041      99   3.000000
1          1          12713      99   2.000000
2          1          21014      99   2.500000
3          1          26938      99   2.000000
4          1          34802      99   2.000000
5          8          27918     124  11.000000
6          8          33190     124  10.000000
7          9           9187      97  10.000000
8          9          12710      97  10.000000
9          9          16228      97  15.000000
10         9          26931      97  15.000000
11        10          16583     131   1.000000
12        10          18403     131   1.000000
13        10          24461     131   1.500000
14        10          29102     131   1.000000
15        10          35257     131   1.000000
16        12           7079      66  20.000000
17        12           9914      66  10.000000
18        12          12575      66  20.000000
19        12          16073      66  14.333333
20        12          20829      66  11.000000
21        12          26723      66  20.000000
22        13          23837      78   5.000000
23        13          26839      78   3.000000
24        13          34692      78   3.000000
25        15          26802      74   1.000000
26        15          34647      74   1.000000
27        21           5721       9   3.000000
28        21           9688       9   2.000000
29        21          12333       9   3.000000
...      ...            ...     ...        ...
1719    2359          12668      85  10.000000
1720    2359          16182      85  10.000000
1721    2359          20957      85  10.000000
1722    2359          26874      85  10.000000
1723    2359          34729      85  14.000000
1724    2361          19358      82  10.000000
1725    2361          26853      82  20.000000
1726    2365          19742     133   1.000000
1727    2365          22128     133   1.000000
1728    2365          25858     133   1.000000
1729    2368          10039      99   5.000000
1730    2368          12711      99  10.000000
1731    2368          21012      99   5.000000
1732    2368          34800      99  13.333333
1733    2379           5749      54   3.000000
1734    2379           7684      54   6.500000
1735    2379          16007      54   3.000000
1736    2379          26642      54   3.000000
1737    2379          34462      54   5.000000
1738    2383           7522       8   2.000000
1739    2383          12326       8   3.000000
1740    2383          26391       8   6.500000
1741    2384           5934      27   1.000000
1742    2384           9777      27  20.000000
1743    2384          12428      27   1.000000
1744    2384          15918      27   3.666667
1745    2384          20652      27   2.000000
1746    2384          26532      27   1.000000
1747    2386          22026      77   3.000000
1748    2387          28629     157  11.250000

[1749 rows x 4 columns]

Join buying user age to user session df

In [4]:
combinedDF = pd.merge(hitsPerUserSession, buysPerUserSession, on = ['userId', 'userSessionId', 'teamId'])
combinedDF.sort(['userId', 'userSessionId'])


/home/cloudera/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


userId  userSessionId  teamId  teamLevel  hitCounts   avgPrice
0          1          10041      99          3          9   3.000000
1          1          12713      99          4         14   2.000000
2          1          21014      99          6         11   2.500000
3          1          26938      99          7         16   2.000000
4          1          34802      99          8         12   2.000000
5          8          27918     124          5         23  11.000000
6          8          33190     124          6         14  10.000000
7          9           9187      97          2          1  10.000000
8          9          12710      97          4         11  10.000000
9          9          16228      97          5          8  15.000000
10         9          26931      97          7         13  15.000000
11        10          16583     131          1         64   1.000000
12        10          18403     131          2         81   1.000000
13        10          24461     131          4         50   1.500000
14        10          29102     131          5         29   1.000000
15        10          35257     131          6         16   1.000000
16        12           7079      66          1          2  20.000000
17        12           9914      66          3          8  10.000000
18        12          12575      66          4          8  20.000000
19        12          16073      66          5         17  14.333333
20        12          20829      66          6         12  11.000000
21        12          26723      66          7         23  20.000000
22        13          23837      78          6         10   5.000000
23        13          26839      78          7         23   3.000000
24        13          34692      78          8         15   3.000000
25        15          26802      74          7         14   1.000000
26        15          34647      74          8          6   1.000000
27        21           5721       9          1          2   3.000000
28        21           9688       9          3          4   2.000000
29        21          12333       9          4          9   3.000000
...      ...            ...     ...        ...        ...        ...
1719    2359          12668      85          4         14  10.000000
1720    2359          16182      85          5         15  10.000000
1721    2359          20957      85          6         28  10.000000
1722    2359          26874      85          7         19  10.000000
1723    2359          34729      85          8         16  14.000000
1724    2361          19358      82          5          2  10.000000
1725    2361          26853      82          7         12  20.000000
1726    2365          19742     133          3         11   1.000000
1727    2365          22128     133          4         25   1.000000
1728    2365          25858     133          5         16   1.000000
1729    2368          10039      99          3         11   5.000000
1730    2368          12711      99          4         11  10.000000
1731    2368          21012      99          6          6   5.000000
1732    2368          34800      99          8          2  13.333333
1733    2379           5749      54          1          9   3.000000
1734    2379           7684      54          2          9   6.500000
1735    2379          16007      54          5          6   3.000000
1736    2379          26642      54          7         14   3.000000
1737    2379          34462      54          8          4   5.000000
1738    2383           7522       8          2         23   2.000000
1739    2383          12326       8          4         24   3.000000
1740    2383          26391       8          7         14   6.500000
1741    2384           5934      27          1          5   1.000000
1742    2384           9777      27          3          6  20.000000
1743    2384          12428      27          4         15   1.000000
1744    2384          15918      27          5         16   3.666667
1745

Filter out NaN rows and select features (age, totalAdClicks, totalPrice)

In [5]:
cleanedDF = combinedDF.dropna()
trainingDF = cleanedDF[['teamLevel', 'hitCounts', 'avgPrice']]
trainingDF.head(5)

teamLevel  hitCounts  avgPrice
0          3          9       3.0
1          4         14       2.0
2          6         11       2.5
3          7         16       2.0
4          8         12       2.0

In [6]:
trainingDF.shape

(1749, 3)

In [7]:
sqlContext = SQLContext(sc)
pDF = sqlContext.createDataFrame(trainingDF)
parsedData = pDF.rdd.map(lambda line: array([line[0], line[1], line[2]])) #'age', 'totalAdClicks','totalPrice'

In [8]:
pDF.describe().toPandas()

summary           teamLevel           hitCounts           avgPrice
0   count                1749                1749               1749
1    mean    5.35620354488279  15.580903373356204  7.281170192490949
2  stddev  1.9756940082869674  12.889155193769643  6.512146813285836
3     min                   1                   0                1.0
4     max                   8                 100               20.0

In [17]:
my_kmmodel = KMeans.train(parsedData, 10, maxIterations=10, runs=10, initializationMode="random", seed = 1234)

/usr/lib/spark/python/pyspark/mllib/clustering.py:176: UserWarning: Support for runs is deprecated in 1.6.0. This param will have no effect in 1.7.0.
  "Support for runs is deprecated in 1.6.0. This param will have no effect in 1.7.0.")


In [18]:
centers = my_kmmodel.centers
centers

[array([  5.44983819,  10.82524272,   2.6639698 ]),
 array([ 5.45508982,  5.45508982,  2.64171657]),
 array([  5.30088496,   5.65486726,  10.86946903]),
 array([  4.2920354 ,  41.98230088,   6.85412979]),
 array([  5.11805556,  26.9375    ,   4.78043981]),
 array([  3.        ,  70.94285714,   6.32857143]),
 array([  6.08152174,  14.01086957,  11.36766304]),
 array([  5.29752066,  21.09917355,  18.42355372]),
 array([  5.41509434,   8.0754717 ,  19.53092243]),
 array([  5.54852321,  16.55696203,   2.91265823])]