## Video 2.1 Creating NumPy Arrays

NumPy is the core library for scientific computing in Python

This section is about the `ndarray` data structure

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4]
x = np.array(my_list)
x

array([1, 2, 3, 4])

In [3]:
type(x)

numpy.ndarray

In [4]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

### Multidimensional arrays

In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
x.size

6

In [7]:
x.shape

(2, 3)

In [8]:
x.ndim

2

In [9]:
x.dtype

dtype('int32')

In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype="float")
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [11]:
x.dtype

dtype('float64')

In [12]:
y = x.astype('int')
y

array([[1, 2, 3],
       [4, 5, 6]])

### Built-in functions for creating arrays

In [13]:
x = np.zeros((3, 2))
x

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [14]:
x = np.ones((2, 3))
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
x = np.eye(4)
x

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
x = np.diag([1, 2, 3])
x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
x = np.arange(0, 10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x = np.arange(0, 20, 2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
x = np.linspace(0, 3, 7)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ])

In [20]:
len(x)

7

In [21]:
[1, 2] * 3

[1, 2, 1, 2, 1, 2]

In [22]:
x = np.array([1, 2] * 3)
x

array([1, 2, 1, 2, 1, 2])

In [23]:
x = np.repeat([1, 2], 3)
x

array([1, 1, 1, 2, 2, 2])

### Stacking

In [25]:
ones = np.ones((2, 3))
ones

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [26]:
twos = ones * 2
twos

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [ ]:
x = np.vstack([ones, twos])
x

In [ ]:
x = np.hstack([ones, twos])
x