## Video 2.3 - Reshaping, Indexing and Slicing

Advanced NumPy operations on arrays

In [1]:
import numpy as np

### Reshaping

In [2]:
x = np.array([1, 2, 3, 4, 5, 6])

x.resize(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
x = np.array([1, 2, 3, 4, 5, 6])

y = x.reshape(2, 3)
x

array([1, 2, 3, 4, 5, 6])

In [4]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
from random import randint

some_number = randint(1, 3)

x = np.arange(5 * some_number)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
y = x.reshape(5, -1)
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
y = x.reshape(-1, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
y = x.reshape(4, -1)  # raises ValueError

ValueError: cannot reshape array of size 15 into shape (4,newaxis)

### Indexing and Slicing

In [9]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [10]:
x[2]

2

In [11]:
x[2:4]

array([2, 3])

In [12]:
x[2:4] = 100
x

array([  0,   1, 100, 100,   4,   5])

#### Broadcasting vs copying

In [13]:
x = np.arange(6)

x_slice = x[2:4]
x_slice

array([2, 3])

In [14]:
x

array([0, 1, 2, 3, 4, 5])

In [15]:
x_slice[:] = 100
x

array([  0,   1, 100, 100,   4,   5])

In [16]:
x = np.arange(6)

x_slice = x[2:4].copy()

x_slice[:] = 100

x

array([0, 1, 2, 3, 4, 5])

In [17]:
x_slice

array([100, 100])

#### Two-dimensional indexing and slicing

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
x[0]  # first row

array([1, 2, 3])

In [20]:
x[0][2]  # third element of the first row

3

In [21]:
x[0, 2]  # same as above

3

In [22]:
x[:, 0]  # first column

array([1, 4, 7])

In [23]:
x[0:2, 1:]

array([[2, 3],
       [5, 6]])

#### Boolean indexing

In [24]:
names = np.array(['Bob', 'Alice', 'Charles', 'Bob', 'Billie', 'Bob'])

data = np.random.randint(0, 10, (6, 3))
data

array([[1, 5, 8],
       [1, 5, 3],
       [4, 0, 8],
       [1, 7, 4],
       [2, 7, 5],
       [2, 2, 6]])

In [25]:
names == 'Bob'

array([ True, False, False,  True, False,  True], dtype=bool)

In [26]:
data[names == 'Bob']

array([[1, 5, 8],
       [1, 7, 4],
       [2, 2, 6]])